name: Push to Staging

on:
  push:
    branches:
      - staging

jobs:
  merge_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Unit Tests
        run: python -m unittest unittest_app.py

      - name: Merge Staging to Main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: staging
          target_branch: main
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
